### ISSUE TITLE
Question: Any discord or project chat?

### ISSUE THREAD

**Issue by jgknight** [mk6i/retro-aim-server#11]
I was curious to know if there is a discord or other place this is being developed? I'd like to at least follow the progress and potentially help contribute.

**Comment by mk6i** [comment]
I was considering making a Discord, and now you've given me the push to actually do it. I'll set one up this weekend. Excited to collab!

**Comment by mk6i** [comment]
All right I set up a server: https://discord.gg/2Xy4nF3Uh9
