### ISSUE TITLE
ICQ support?

### ISSUE THREAD

**Issue by siohaza** [mk6i/retro-aim-server#13]
As far as I know AIM and ICQ both leverage OSCAR protocol, would it be possible add support for ICQ?
It should be documented [here](https://ox.github.io/iserverd-oscar-mirror)

**Comment by mk6i** [comment]
Definitely plan to implement support for icq in a few months. Of course, it could be done sooner if someone volunteered before then. :) Shouldn’t be a big lift.

**Comment by mk6i** [comment]
With the imminent shutdown of ICQ, it might make sense to prioritize this

**Comment by mherrmann95** [comment]
> With the imminent shutdown of ICQ, it might make sense to prioritize this

Thank you, I'm looking forward to it!

**Comment by mk6i** [comment]
Update: Got a prototype working for ICQ 2000b. Now I’m rewriting the code. Should be available in 2 weeks or so.

**Comment by RealBradCool** [comment]
Any updates on the icq. Im having issues when using the icqwip-3 branch as my retro aim server

**Comment by mk6i** [comment]
ICQ is still in progress. Working on login issues currently.

**Comment by RealBradCool** [comment]
yeah i could help.

**Comment by mk6i** [comment]
What issues are you seeing? And what version of ICQ?

**Comment by RealBradCool** [comment]
um ICQ 2000b

**Comment by RealBradCool** [comment]
1. when i go on icq 2000b with the icq server branch it thinks im offline and it spams stuff like that the icq disconnect and connected and icq logon

**Comment by mk6i** [comment]
Try setting OSCAR_HOST=login.oscar.aol.com in config.

Also, feel free to join our Discord to discuss

**Comment by RealBradCool** [comment]
uh it does not reach it it now says that can not be reached because i changed the oscar host to login.oscar.aol.com is there an other fix

**Comment by mk6i** [comment]
Whoops also forgot to mention to add a hosts entry that points login.oscar.aol.com to 127.0.0.1, assuming you run ICQ and RAS on the same machine.

**Comment by mk6i** [comment]
Update: All the major hurdles for supporting ICQ 2000b have been cleared, now I'm just rounding out features and writing tests.

**Comment by mk6i** [comment]
ICQ 2000b support has been merged into main. Aiming to do a release this weekend. :)

If you all wanted to give it a spin, start with the [ICQ client setup guide](https://github.com/mk6i/retro-aim-server/blob/main/docs/CLIENT_ICQ.md).

**Comment by mk6i** [comment]
Support for ICQ 2000b is now available in [v0.10.0](https://github.com/mk6i/retro-aim-server/releases/tag/v0.10.0).
