### ISSUE TITLE
Cant connect to the AIM self hosted server on a VM

### ISSUE THREAD

**Issue by vipsrbfanpage** [mk6i/retro-aim-server#25]
![image](https://github.com/mk6i/retro-aim-server/assets/103321416/6af0b66e-90ae-4bfe-a102-57c4c6edd7ea)

**Comment by mk6i** [comment]
Thanks for reporting. It looks like there might be a networking issue.

I don't have much to go with here. Would you please post more details, including:
- your server config file
- screenshot of your aim client server config window
- server logs

What's your virtualbox network setting mode? Bridged?

**Comment by mk6i** [comment]
Closing this issue since it's been a week with no follow-up. Feel free to reopen if need be.
