### ISSUE TITLE
Pidgin 2.12.0 Linux

### ISSUE THREAD

**Issue by rhandorf** [mk6i/retro-aim-server#31]
I've compiled Pidgin 2.12.0 from source here: https://www.linuxfromscratch.org/blfs/view/8.1/xsoft/pidgin.html

It can log in and send messages to native AIM client. But when receiving messages only shows "[username] is typing".

Here's a trace. I've removed the IP's and username in use.

time=2024-05-20T18:21:34.876-04:00 level=INFO msg="user sent an IM" svc=BOS recipient=[userA] screenName=[userB] ip=[snip]:36948
time=2024-05-20T18:21:34.876-04:00 level=TRACE msg="client request -> server response" svc=BOS request.food_group=ICBM request.sub_group=ICBMChannelMsgToHost request.snac_frame="{FoodGroup:4 SubGroup:6 Flags:0 RequestID:22}" request.snac_payload="{Cookie:3833467301336265728 ChannelID:1 ScreenName:[userA] TLVRestBlock:{TLVList:[{Tag:2 Value:[5 1 0 4 1 1 1 2 1 1 0 34 0 0 0 0 60 72 84 77 76 62 60 66 79 68 89 62 116 101 115 116 60 47 66 79 68 89 62 60 47 72 84 77 76 62]} {Tag:3 Value:[]} {Tag:6 Value:[]}]}}" response.food_group=ICBM response.sub_group=ICBMHostAck response.snac_frame="{FoodGroup:4 SubGroup:12 Flags:0 RequestID:22}" response.snac_payload="{Cookie:3833467301336265728 ChannelID:1 ScreenName:[userA]}" screenName=[userB] ip=[snip]:36948
time=2024-05-20T18:21:34.876-04:00 level=TRACE msg="client request" svc=BOS request.food_group=ICBM request.sub_group=ICBMChannelMsgToClient request.snac_frame="{FoodGroup:4 SubGroup:7 Flags:0 RequestID:0}" request.snac_payload="{Cookie:3833467301336265728 ChannelID:1 TLVUserInfo:{ScreenName:[userB] WarningLevel:0 TLVBlock:{TLVList:[]}} TLVRestBlock:{TLVList:[{Tag:11 Value:[]} {Tag:2 Value:[5 1 0 4 1 1 1 2 1 1 0 34 0 0 0 0 60 72 84 77 76 62 60 66 79 68 89 62 116 101 115 116 60 47 66 79 68 89 62 60 47 72 84 77 76 62]} {Tag:3 Value:[]} {Tag:6 Value:[]}]}}" screenName=[userA] ip=[snip]:37175
time=2024-05-20T18:21:37.258-04:00 level=TRACE msg="client request" svc=BOS request.food_group=ICBM request.sub_group=ICBMClientEvent request.snac_frame="{FoodGroup:4 SubGroup:20 Flags:0 RequestID:20}" request.snac_payload="{Cookie:0 ChannelID:1 ScreenName:[userB] Event:2}" screenName=[userA] ip=[snip]:37175
time=2024-05-20T18:21:37.258-04:00 level=TRACE msg="client request" svc=BOS request.food_group=ICBM request.sub_group=ICBMClientEvent request.snac_frame="{FoodGroup:4 SubGroup:20 Flags:0 RequestID:20}" request.snac_payload="{Cookie:0 ChannelID:1 ScreenName:[userA] Event:2}" screenName=[userB] ip=[snip]:36948
time=2024-05-20T18:21:37.985-04:00 level=INFO msg="user sent an IM" svc=BOS recipient=[userB] screenName=[userA] ip=[snip]:37175
time=2024-05-20T18:21:37.985-04:00 level=TRACE msg="client request" svc=BOS request.food_group=ICBM request.sub_group=ICBMChannelMsgToClient request.snac_frame="{FoodGroup:4 SubGroup:7 Flags:0 RequestID:0}" request.snac_payload="{Cookie:3833467301336265728 ChannelID:1 TLVUserInfo:{ScreenName:[userA] WarningLevel:0 TLVBlock:{TLVList:[]}} TLVRestBlock:{TLVList:[{Tag:11 Value:[]} {Tag:2 Value:[5 1 0 3 1 1 2 1 1 0 74 0 0 0 0 60 72 84 77 76 62 60 66 79 68 89 32 66 71 67 79 76 79 82 61 34 35 102 102 102 102 102 102 34 62 60 70 79 78 84 32 76 65 78 71 61 34 48 34 62 112 111 110 103 60 47 70 79 78 84 62 60 47 66 79 68 89 62 60 47 72 84 77 76 62]}]}}" screenName=[userB] ip=[snip]:36948

**Comment by mk6i** [comment]
I tried compiling Pidgin 2.12.0 on Ubuntu and was unable to reproduce the issue.

- What version of RAS were you running?
- What was the AIM client version on the other end?
- Do you have the same problem with v0.6.0?

**Comment by rhandorf** [comment]
Just pulled the latest server source, ran it, and it works!
