### ISSUE TITLE
Error when starting server(Management API error?)

### ISSUE THREAD

**Issue by josephlombardo1** [mk6i/retro-aim-server#33]
### Subject of the issue
Management API error

### Deployment environment

* retro-aim-server version: 0.5.0

* Install method: Pre-built

* Clients used: 
None(Server not working)
* Other relevant details:
Using Ubuntu 22.04
### Steps to reproduce

I started the server frome run.sh
### Expected behaviour

I expected the server to run as it should
### Actual behaviour

It might have started the server but couldn't get the Management API
### Troubleshooting data

Terminal Printout:

`time=2024-05-25T17:28:44.881Z level=INFO msg="starting auth service" svc=AUTH host=127.0.0.1:5190
time=2024-05-25T17:28:44.882Z level=INFO msg="starting management API server" addr=:8080
time=2024-05-25T17:28:44.882Z level=ERROR msg="unable to bind management API address address" err="listen tcp :8080: bind: address already in use"`

**Comment by josephlombardo1** [comment]
I'm not hosting any web server or anything i know of with the port 8080. It says its in use.

**Comment by mk6i** [comment]
Hey there, try setting the port value `API_PORT` in `settings.env` to something that's not currently being used, like 8081. Make sure to update the port value in the cURL requests in `README.md` accordingly if you do any server operations.

**Comment by mk6i** [comment]
Closing this as it seems like a pretty simple fix, feel free to reopen if need be.

**Comment by josephlombardo1** [comment]
Hello again. I checked the whole settings.env file and found 0 trace of any lines with the word API_PORT. Maybe a mistake in the 0.5.0 pre-compiled release?

**Comment by mk6i** [comment]
My mistake! This setting is in main but has not yet been released. It'll be available in the v0.6.0 release, I'll tag you here when its's out.

**Comment by josephlombardo1** [comment]
Heres the error i get now

`time=2024-05-27T18:07:55.379Z level=INFO msg="starting auth service" svc=AUTH host=127.0.0.1:5190
time=2024-05-27T18:07:55.379Z level=INFO msg="starting management API server" addr=:8080
time=2024-05-27T18:07:55.380Z level=ERROR msg="unable to bind management API address address" err="listen tcp :8080: bind: address already in use`

**Comment by josephlombardo1** [comment]
It didn't work

**Comment by mk6i** [comment]
What didn't work? You pulled the main branch and modified the port number?

**Comment by josephlombardo1** [comment]
No, I just took the settings.env file. Maybe thats why it didnt work

**Comment by mk6i** [comment]
ah yes you will need the latest code too

**Comment by josephlombardo1** [comment]
K, I will try to compile the code

**Comment by josephlombardo1** [comment]
I pulled the main branch, installed go and ran the run.sh file(it seemed run_dev.sh was taking too long) and got this error
`error: environment file '/home/user/Downloads/retro-aim-server-main/scripts/settings.env' not found.`
Moved a settings.env file to it and got this
`error: executable '/home/user/Downloads/retro-aim-server-main/scripts/bin/retro_aim_server' not found.`
I think its looking for the pre-compiled release files. I'll try adding them.

**Comment by mk6i** [comment]
Have you checked out [these docs](https://github.com/mk6i/retro-aim-server/blob/main/docs/BUILD.md)? `run_dev.sh` is the one you want. It may take a little while to start because the builder has to download dependencies and compile the sources.

**Comment by mk6i** [comment]
API port setting was released in v0.6.0, feel free to reopen if needed.
