### ISSUE TITLE
Running guide for linux

### ISSUE THREAD

**Issue by brannanz** [mk6i/retro-aim-server#5]
I tried and failed, please create a guide for running

**Comment by mk6i** [comment]
@brannanz thanks for the feedback. I do have documentation in the works for win/macos/linux. What are you struggling with? Starting the server, AIM client, or both?

**Comment by mk6i** [comment]
I was able to run the project on a fresh install of Ubuntu 22.04:

```sh
sudo snap install go --classic
bash --login # restart terminal
./scripts/run_dev.sh
```

What version of go are you running?

**Comment by mk6i** [comment]
I was able to run the project on a fresh install of Ubuntu 22.04. Note that you'll need gcc and go 1.21.1+.

```sh
sudo apt install build-essential # gcc is required for the sqlite driver
sudo snap install go --classic
bash --login # restart terminal
./scripts/run_dev.sh
```

**Comment by mk6i** [comment]
@brannanz I just pushed some improvements to the quick start guide in the README, hope you find them helpful.

**Comment by mk6i** [comment]
Any luck @brannanz?
