### ISSUE TITLE
2 Issues with the classic Mac OS AIM client

### ISSUE THREAD

**Issue by D3CL4NZ** [mk6i/retro-aim-server#56]
### Subject of the Issue
- Block button does not appear in the IM window.
- Chat button is greyed out.

### Deployment Environment
* **Retro AIM Server Version**: [fa33cdf](https://github.com/mk6i/retro-aim-server/commit/fa33cdf87b648bee86d67970d884cc28daad93c0)
* **Installation Method**: Built from source
* **Client(s) Used**: AIM v4.0.972 on Mac OS 9.2.1
* **Other Relevant Details**: After clicking "change password", the Chat button works again.

### Steps to Reproduce
1. Start an IM with someone.

### Expected Behavior
- Both buttons will work properly.

### Actual Behavior
- Block button does not appear in the IM window.
- Chat button is greyed out.

### Troubleshooting Data
<img width="1024" alt="Screenshot 2024-07-26 at 3 45 26 PM" src="https://github.com/user-attachments/assets/e8522bcd-ca36-4f5a-8a5a-46c12ebb0aa6">
<img width="440" alt="Screenshot 2024-07-26 at 3 46 02 PM" src="https://github.com/user-attachments/assets/857050e5-1c57-4518-a2ca-98a115753f50">

**Comment by RealBradCool** [comment]
maybe your running it on a apple macintosh i think it only works on new devices. I'm working on a fix to that client with Brent Instant messenger also known as BIM.

**Comment by D3CL4NZ** [comment]
The whole point is for it to work on old clients as well, so I don't think it requires a new device. It works just fine on Windows 98
