### ISSUE TITLE
How to join a chat room i created?

### ISSUE THREAD

**Issue by floridainsummer505** [mk6i/retro-aim-server#71]
i created a chat room though management api, but idk how to join it

**Comment by mk6i** [comment]
Get the list of chat rooms using the [List Public Chat Rooms](https://github.com/mk6i/retro-aim-server?tab=readme-ov-file#list-public-chat-rooms) endpoint.

The payload looks like this:

```json
[
  {
    "name": "Office Hijinks",
    "create_time": "2024-10-23T12:47:23.75476Z",
    "url": "aim:gochat?roomname=Office+Hijinks&exchange=5",
    "participants": []
  }
]
```

Copy the url `aim:gochat?roomname=Office+Hijinks&exchange=5` and send it to yourself in an IM. Click the link, which should bring you to the chat.

**Comment by floridainsummer505** [comment]
Ok
