### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by Kayabulba70BMC** [mk6i/retro-aim-server#8]
I set DISABLE_AUTH=false but when I create accounts via the API, I got "User account created" message. But when I try to login, It says invalid screenname or password. How to fix it?
Also sorry for bad English.

**Comment by mk6i** [comment]
Hello, what version AIM client are you using?

**Comment by mk6i** [comment]
Also, please share the API request you are sending to create the account (with redacted password if it’s sensitive).

**Comment by Kayabulba70BMC** [comment]
I use AIM 5.1 on Windows XP. I executed command `curl -d'{"screen_name":"asd", "password":"asd"}' http://localhost:8080/user` also tried other usernames and passwords. But disabling the auth works.

**Comment by mk6i** [comment]
That is weird. Does the password “welcome1” work for user asd?

**Comment by mk6i** [comment]
Basically, try launching the server with `DISABLE_AUTH=true` and logging in with username `asd` and password `welcome`.

**Comment by mk6i** [comment]
Basically, try launching the server with `DISABLE_AUTH=true` and logging in with username `asd` and password `welcome1`.

**Comment by Kayabulba70BMC** [comment]
When I try `DISABLE_AUTH=true` it logins.

**Comment by mk6i** [comment]
Oops sorry I mean:

Basically, try launching the server with `DISABLE_AUTH=false` and logging in with username `asd` and password `welcome1`.

`DISABLE_AUTH` is a little confusing. :)

**Comment by Kayabulba70BMC** [comment]
Also the password `welcome1` not works when I try `DISABLE_AUTH=false`.

**Comment by mk6i** [comment]
Hmm one last thing before I dig deeper:

1) Set `DISABLE_AUTH=false`
2) Run `curl -d'{"screen_name":"asd123", "password":"asd123"}' http://localhost:8080/user`
3) Try to login `asd123`

Can you please upload your `oscar.sqlite` file here?

**Comment by Kayabulba70BMC** [comment]
Same error again. Here is my oscar.sqlite file: (I deleted the previous one and created asd123 account.)
[oscar.zip](https://github.com/mk6i/retro-aim-server/files/15139588/oscar.zip)

**Comment by mk6i** [comment]
Thanks for your report. What OS are you running the server on? Are you running v0.2.0?

**Comment by Kayabulba70BMC** [comment]
Yes I'm using v0.2.0 (also tried v0.1.0 but same error). I'm running the server in Windows 10. I tried the Git bash and also PHP for curl but the same error. (I looked at the database and the accounts was created. And gives User account created successfully message.)

**Comment by mk6i** [comment]
I'm able to repro with your DB file. The question is how does the wrong password get in there? Hmm.

**Comment by mk6i** [comment]
[oscar.sqlite.mk6i.zip](https://github.com/mk6i/retro-aim-server/files/15139632/oscar.sqlite.mk6i.zip)

Would you please try my sqlite file? Username: asd123 Password: asd123

**Comment by Kayabulba70BMC** [comment]
Thanks! This DB file works with the account. But what is the problem?

**Comment by mk6i** [comment]
My first guess is that the Window command prompt is doing something weird. Can you try running the curl command, but passing in the JSON payload through the attached file?

First delete the DB file then run this request to populate the user with `DISABLE_AUTH=false`.
[input.json](https://github.com/mk6i/retro-aim-server/files/15139658/input.json)

```
curl -H "Content-Type: application/json" -d "@input.json" http://localhost:8080/user
```

**Comment by Kayabulba70BMC** [comment]
The code worked. This problem is caused by I used the wrong PHP code. Thanks for your help.

**Comment by mk6i** [comment]
Thanks for the update @Kayabulba70BMC! Glad it got sorted out.

> Also sorry for bad English.

Your english is excellent btw :)
